apiVersion: v1
kind: Namespace
metadata:
  name: fghbjhfbghfg-prod
  labels:
    environment-id: env_18313cb5-9d43-41dd-ab89-ddf540665bad
    project-id: project_59b6944a-b3e4-41f6-b371-b7d60dbfb1ee
    project-name: fghbjhfbghfg
    environment-name: prod
    organization-id: org_99bfadb5-996a-47d5-a5fc-442c14a28627
