apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |2-

                  exec:
                    path: skyu-app-transformer
                
type: service
applicationContainers:
  - name: main-container
    imageRegistry: test
    imageTag: latest
    cpuRequestMili: 100
    cpuLimitMili: 200
    memoryRequestMb: 100
    memoryLimitMb: 200
    applicationPorts:
      - port: 80
        protocol: TCP
minReplicas: 1
maxReplicas: 1
terminationGracePeriodSeconds: 60
namespace: default
name: discord
labels:
  app: discord
  application-id: app_88d90a4f-5a73-4e4c-85f3-60b02e09820d
  project-id: project_efd04c7e-bf4a-478d-b2cf-c8e840ce4ccf
  organization-id: org_01b50229-db34-43d4-8f3e-d1aeb683d900
  environment-id: env_26af9436-92aa-40b0-92f7-b09234d25a68
  environment-name: staging
serviceType: ClusterIP
